- package.json
- yarn.lock
[ Added chakra UI](https://chakra-ui.com/)
[Added react icons](https://react-icons.github.io/react-icons/)
> Setup chakra UI and React Icons

- src/Admin.tsx
- src/components/FederationCard.tsx
- src/components/Header.tsx
- src/federation.data.ts
- src/federation.types.ts
Added functions to implement filter and sort functionality for federations list
> implemented filter and sort feature

- src/Admin.tsx
- src/components/Button.tsx
- src/components/ConnectFederation.tsx
- src/components/Header.tsx
- src/components/Input.tsx
- src/components/index.tsx
- src/index.tsx
Created ConnectFederation component 
Remodified button to accept props for connect federation implementation 
Created reusable input component 
changed connect federation header button to accept props for access to connect fed component
> Feature Connect fed

- src/components/FederationCard.tsx
- src/components/InfoTab.tsx
- src/components/index.tsx
I liked the tab system introduced by @IgboPharaoh in our chats. This PR sets up a tab system within federation card so we can build more experiences like _Deposit_ and _Withdraw_ in a compact style within the same federation card
> Introduce tab system

- src/components/DepositTab.tsx
- src/components/FederationCard.tsx
- src/components/index.tsx
Sketch out a gateway deposit experience with the following steps
1. Gateway admin sees a new deposit address rendered on **Deposit** tab of a connected federation
- the admin is prompted to make a Bitcoin onchain transaction to this address
- they can copy, share or scan the address shown
2. Once payment reflects on the mempool, Deposit tab switches to a pending transaction view
- the admin can see how many transactions are required for the Fedimint peg-in to be considered complete
- they see progress of this transaction towards completion
- they can inspect the transaction through a quick link to a blockchain explorer like [mempool.space](https://mempool.space)
3. Once the right block height is reached, this transaction is considered ready and gateway admin UI automatically completes the …
> Sketch gateway deposit experience (peg-in)

- package.json
- src/components/DepositTab.tsx
- yarn.lock
Render real qr code for the deposit address experience
> Deposit QR code

- src/components/DepositTab.tsx
minor polish item to open txid in new tab
> polish: open txid in new tab

- src/components/FederationCard.tsx
- src/components/Input.tsx
- src/components/WithdrawTab.tsx
From gateway admin dashboard, Admins can request a withdrawal from any federation of their choice.  
The admin provides his address and the amount to receive. 
- Modified input component to accept name to be used as key for passing values into objects. 
- Sketched out withdraw tab and basic UI. 
-  Added withdraw tab to federation card to make it easily accessible through the tab headers
> Feature Withdraw

- .eslintignore
- .eslintrc.json
- .husky/pre-commit
- .prettierrc
- package.json
- public/index.html
- public/manifest.json
- src/Admin.tsx
- src/components/Button.tsx
- src/components/ConnectFederation.tsx
- src/components/ConnectLightning.tsx
- src/components/DepositTab.tsx
- src/components/FederationCard.tsx
- src/components/Header.tsx
- src/components/InfoTab.tsx
- src/components/Input.tsx
- src/components/TabHeader.tsx
- src/components/WithdrawTab.tsx
- src/components/index.tsx
- src/federation.data.ts
- src/federation.types.ts
- src/index.css
- src/index.tsx
- src/reportWebVitals.ts
- tsconfig.json
- yarn.lock
Configure automated lint and fix of source code with every commit
> Automated Lints

- src/Admin.tsx
- src/components/Button.tsx
- src/components/FederationCard.tsx
-Made gateway admin page responsive. 
-Change button font size prop. 
-Made federation card responsive responsive
> UI polish for Admin page 

- src/components/Button.tsx
- src/components/ConnectLightning.tsx
- src/components/Header.tsx
- src/index.css
-Modified button props and types to accept responsive styles. 
-Made connect lightning button to be responsive across screens.  
-Made header responsive. 
-Add menu icon for mobile screens
> Responsiveness Header

- src/components/Button.tsx
- src/components/ConnectFederation.tsx
- src/components/ConnectLightning.tsx
- src/components/DepositTab.tsx
- src/components/FederationCard.tsx
- src/components/Header.tsx
- src/components/WithdrawTab.tsx
Removed label prop from button component, prefer to use child props instead.
> Removed label prop from button component

- src/components/ConnectLightning.tsx
- src/index.css
-Changed button icon to a lightning bolt. 
-Modified connect lightning component to be responsive on mobile screens
> Responsive styles connect lightning

- src/components/InfoTab.tsx
-Made infotab component to be responsive
-Changed initial design structure
> Responsive styles for infotab

- src/components/WithdrawTab.tsx
-Made components in the withdraw tab to be responsive across all screens
> responsive styles for withdraw tab

- src/components/DepositTab.tsx
Fixed text formatting for withdraw screen 1. 
Changed function name for slicing string to be more descriptive
> Text fixes for withdraw tab

- src/components/DepositTab.tsx
Some additional UI polish on the deposit tab
Before:
After:
> Text alignment and other UI polish on deposit tab

- src/api/Mintgate.mock.ts
- src/api/Mintgate.ts
- src/components/DepositTab.tsx
Defines a `fetchAddress` api definition and return mock address. Eventually, we want a real implementation of this API
> Fetch address as api

- src/Admin.tsx
-modified max width for gateway admin view
> set max width for gateway admin view

- src/Admin.tsx
- src/api/Mintgate.mock.ts
- src/api/Mintgate.ts
- src/components/ConnectFederation.tsx
Define connect fed api and write a mock version of it. Wire it to the connect fed experience
> Connect fed api

- src/api/Mintgate.mock.ts
- src/api/Mintgate.ts
- src/components/DepositTab.tsx
Define api call to complete deposit to federation
> Complete deposit API

- src/api/Mintgate.mock.ts
- src/components/WithdrawTab.tsx
-Refactor ConfirmTransactionModals. 
-Refactor withdrawal function to watch the status of newly created transactions. 
-Refactor TransactionViewProps to only show the expanded state when a transaction has been tracked on the chain
-Hardcode transactionId corresponding to hardcoded address
> refactor WithdrawTab for code clarity

- README.md
Added instructions to install dependencies and start development server 
Issue #44
> Towards modifying contribution guidelines

- README.md
- src/components/InfoTab.tsx
> Convert date to human readable

- src/components/Button.tsx
> Added styling to button on hover
